name: Auto Commit

on:
  push:
    branches:
      - main  # Trigger only on main branch changes

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make changes (example: update file)
        run: |
          echo "Auto update at $(date)" >> update.log

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto commit from GitHub Action" || echo "Nothing to commit"
          git push
